# core/doc_exporter.py
# ─────────────────────────────────────────────────────────────────────────────
# Exports generated text to Word (.docx) and PDF files
# In-memory bytes — no file system writes needed (streamed to browser)
# ─────────────────────────────────────────────────────────────────────────────

import io
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER


DOC_LABELS = {
    "brd": "Business Requirements Document",
    "tdd": "Technical Design Document",
    "fdd": "Functional Design Document",
    "s2t": "Source-to-Target Mapping",
    "qa_report": "QA Validation Report",
}


# ─── Word export ─────────────────────────────────────────────────────────────

def to_word(doc_type: str, content: str, dataset_name: str) -> bytes:
    """Generate a Word doc in memory. Returns bytes for download."""
    doc = Document()

    # Title page header
    title = doc.add_heading(DOC_LABELS.get(doc_type, doc_type.upper()), level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(0xC0, 0x39, 0x2B)  # AutoDocAI red

    # Subtitle
    sub = doc.add_paragraph(f"Project: {dataset_name}")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.size = Pt(12)
    sub.runs[0].font.color.rgb = RGBColor(0x64, 0x74, 0x8B)

    # Generated timestamp
    ts = doc.add_paragraph(f"Generated by AutoDocAI  •  {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    ts.alignment = WD_ALIGN_PARAGRAPH.CENTER
    ts.runs[0].font.size = Pt(9)
    ts.runs[0].font.color.rgb = RGBColor(0x94, 0xA3, 0xB8)

    doc.add_paragraph()  # spacer

    # Parse content — handle headings (lines starting with # or numbered like "1.")
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph()
            continue

        # Markdown-style headings
        if stripped.startswith("### "):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("# "):
            doc.add_heading(stripped[2:], level=1)
        # Numbered section headings like "1. Executive Summary"
        elif len(stripped) > 2 and stripped[0].isdigit() and stripped[1] in ".)" and stripped[2] == " ":
            h = doc.add_heading(stripped, level=2)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x0D, 0x1B, 0x2A)
        # Bullet-style lines
        elif stripped.startswith("- ") or stripped.startswith("• "):
            p = doc.add_paragraph(stripped[2:], style="List Bullet")
        elif stripped.startswith("| "):
            # Table row — just render as normal text for simplicity
            doc.add_paragraph(stripped).runs[0].font.size = Pt(9)
        else:
            doc.add_paragraph(stripped)

    # Footer note
    doc.add_paragraph()
    footer = doc.add_paragraph("This document was auto-generated by AutoDocAI. Business narratives and approvals require human validation.")
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(0x94, 0xA3, 0xB8)
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


# ─── PDF export ──────────────────────────────────────────────────────────────

def to_pdf(doc_type: str, content: str, dataset_name: str) -> bytes:
    """Generate a PDF in memory. Returns bytes for download."""
    buf = io.BytesIO()
    pdf = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=inch, rightMargin=inch,
        topMargin=0.8*inch, bottomMargin=0.8*inch,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "AutoTitle", parent=styles["Title"],
        fontSize=22, textColor=colors.HexColor("#C0392B"),
        spaceAfter=4, alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "AutoSubtitle", parent=styles["Normal"],
        fontSize=12, textColor=colors.HexColor("#64748B"),
        spaceAfter=2, alignment=TA_CENTER,
    )
    ts_style = ParagraphStyle(
        "AutoTS", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#94A3B8"),
        spaceAfter=12, alignment=TA_CENTER,
    )
    h1_style = ParagraphStyle(
        "AutoH1", parent=styles["Heading1"],
        fontSize=15, textColor=colors.HexColor("#0D1B2A"),
        spaceBefore=16, spaceAfter=6,
    )
    h2_style = ParagraphStyle(
        "AutoH2", parent=styles["Heading2"],
        fontSize=12, textColor=colors.HexColor("#1A2E42"),
        spaceBefore=10, spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "AutoBody", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#1E293B"),
        spaceAfter=4, leading=16,
    )
    footer_style = ParagraphStyle(
        "AutoFooter", parent=styles["Normal"],
        fontSize=7, textColor=colors.HexColor("#94A3B8"),
        alignment=TA_CENTER, spaceBefore=20,
    )

    story = [
        Paragraph(DOC_LABELS.get(doc_type, doc_type.upper()), title_style),
        Paragraph(f"Project: {dataset_name}", subtitle_style),
        Paragraph(f"Generated by AutoDocAI  •  {datetime.now().strftime('%Y-%m-%d %H:%M')}", ts_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#C0392B"), spaceAfter=12),
    ]

    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 6))
            continue

        if stripped.startswith("### "):
            story.append(Paragraph(stripped[4:], h2_style))
        elif stripped.startswith("## ") or stripped.startswith("# "):
            story.append(Paragraph(stripped.lstrip("# "), h1_style))
        elif len(stripped) > 2 and stripped[0].isdigit() and stripped[1] in ".)" and stripped[2] == " ":
            story.append(Paragraph(f"<b>{stripped}</b>", h1_style))
        else:
            # Escape XML special chars for ReportLab
            safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, body_style))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceBefore=20))
    story.append(Paragraph(
        "This document was auto-generated by AutoDocAI. Business narratives and approvals require human validation.",
        footer_style
    ))

    pdf.build(story)
    buf.seek(0)
    return buf.read()


# ─── Convenience: export all docs ────────────────────────────────────────────

def export_all(docs: dict, dataset_name: str, fmt: str = "word") -> dict[str, bytes]:
    """
    Export all generated docs to the specified format.
    Returns {doc_type: bytes}
    fmt: "word" or "pdf"
    """
    export_fn = to_word if fmt == "word" else to_pdf
    result = {}
    for doc_type, content in docs.items():
        if doc_type == "audit_score" or not isinstance(content, str):
            continue
        result[doc_type] = export_fn(doc_type, content, dataset_name)
    return result
